# NETLIFY CMS config file 
backend:
  # name: test-repo
  name: git-gateway

media_folder: "static/imgs"
public_folder: "/imgs"
publish_mode: editorial_workflow
collections:
  - name: article
    label: Article
    folder: src/pages/article
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string, default: "Alex Nye"}
      - { name: date, label: Date, widget: datetime, dateFormat: "YYYY-MM-DD" }      
      - { name: learn, label: Learn, widget: boolean, default: true}
      - { name: category, label: Category, widget: string}
      - { name: subcategory, label: Sub-Category, widget: list}
      - { name: tags, label: Tags, widget: list}
      - { name: featuredImage, label: Featured Image, widget: image}
      - { name: metaDescription, label: Meta Description, widget: string}
      - { name: body, label: Body, widget: markdown }


#       ---
# title: Dynamic Plug-In Loading in Logic Pro 10
# author: 'Alex Nye'
# date: '2019-06-16'
# learn: true
# category: 'Studio'
# subcategory: ['Logic']
# tags: ['template', 'logic', 'studio', 'daw']
# featuredImage: './TypesOfReverb_FeaturedImage.jpg'
# metaDescription: 'Explaination of the 5 different types of reverbs, what they sound like, and when to chooose a certain reverb.'
# ---