# NETLIFY CMS config file 
backend:
  name: test-repo
  # name: git-gateway

media_folder: "static/imgs"
public_folder: "/imgs"
publish_mode: editorial_workflow
collections:
  - name: article
    label: Article
    folder: src/pages/article
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: author, label: Author, widget: string, default: "Alex Nye"}
      - { name: date, label: Date, widget: datetime, dateFormat: "YYYY-MM-DD" }      
      # - { name: learn, label: Learn, widget: boolean, default: true}
      - { name: category, label: Category, widget: select, options: ["Knowledge", "Reviews", "Music News", "Blog"]}
      - { name: subcategory, label: Sub-Category, widget: select, 
          options: [
                    {label: "Knowledge - Tutorial", value: "Tutorial"},
                    {label: "Knowledge - Basics", value: "Basics"},
                    {label: "Knowledge - Mixing", value: "Mixing"},
                    {label: "Knowledge - Gear", value: "Gear"},
                    {label: "Knowledge - Logic Pro X", value: "Logic Pro X"},
                    {label: "Knowledge - Sound Design", value: "Sound Design"},
                    {label: "Knowledge - Music Theory", value: "Music Theory"},
                    {label: "Knowledge - Business", value: "Business"},
                    {label: "Knowledge - Analysis", value: "Analysis"},
                    {label: "Review - EQ", value: "EQ"},
                    {label: "Review - Compressors", value: "Compressor"},
                    {label: "Review - Synth", value: "Synth"},
                    {label: "Review - Outboard", value: "Outboard Gear"},
                    {label: "Review - Free", value: "Free"},
                    {label: "Review - Educational", value: "Educational"},
                    {label: "Review - Books", value: "Books"},
                    {label: "Review - Sample Instrument", value: "Sample Instrument"},
                    {label: "Review - Samples", value: "Samples"},
                    {label: "Review - Presets", value: "Presets"},
                    {label: "Review - Amp Simulator", value: "Amp Simulator"},
                    {label: "News - New Gear", value: "New Gear"},
                    {label: "News - Music News", value: "Music News"},
                    {label: "News - Obituaries", value: "Obituaries"},
                    {label: "News - Business", value: "Business News"},
                    {label: "Blog - Artists Life", value: "Artist's Life"},
                    {label: "Blog - Humble Opinion", value: "Humble Opinion"},
                    ]
        }
      - { name: tags, label: Tags, widget: list}
      - { name: featuredImage, label: Featured Image, widget: image}
      - { name: metaDescription, label: Meta Description, widget: string}
      - { name: body, label: Body, widget: markdown }


#       ---
# title: Dynamic Plug-In Loading in Logic Pro 10
# author: 'Alex Nye'
# date: '2019-06-16'
# learn: true
# category: 'Studio'
# subcategory: ['Logic']
# tags: ['template', 'logic', 'studio', 'daw']
# featuredImage: './TypesOfReverb_FeaturedImage.jpg'
# metaDescription: 'Explaination of the 5 different types of reverbs, what they sound like, and when to chooose a certain reverb.'
# ---